version: 0.1

phases:
  pre_build:
    commands:
      - echo Installing node_modules
      - yarn install
  build:
    commands:
      - echo Build started on `date`
      - echo Building seanmclane.com
      - gatsby build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
  base-directory: public