version: 0.1

phases:
  pre_build:
    commands:
      - echo Installing node_modules
      - yarn install
  build:
    commands:
      - echo Build started on `date`
      - echo Building seanmclane.com
      - gatsby build
  post_build:
    commands:
      - echo "******** Uploading to S3 ********"
      - aws s3 sync public/ s3://dev.seanmclane.com
      - echo Build completed on `date`