version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing yarn
      - curl -sS http://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
      - echo "deb http://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
      - apt-get update
      - apt-get install -y yarn
      - echo Installing node_modules
      - yarn install
      - echo Installing gatsby
      - yarn global add gatsby
  build:
    commands:
      - echo Building seanmclane.com
      - gatsby build
      - echo Compressing files
      - gzip -r public/
  post_build:
    commands:
      - echo "******** Uploading to S3 ********"
      - aws s3 sync --delete public/ s3://${BUCKET_NAME} --content-encoding 'gzip'