version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo Installing yarn
      - curl -sS http://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
      - echo "deb http://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
      - apt-get update
      - apt-get install -y yarn
      - echo Installing node_modules
      - yarn install
      - echo Installing gatsby
      - yarn global add gatsby@2.15.35
  build:
    commands:
      - echo Building seanmclane.com
      - gatsby build
      - echo Compressing files
      - gzip -r public/
      - find public/. -name '*.gz' -type f | while read NAME ; do mv "${NAME}" "${NAME%.gz}" ; done
  post_build:
    commands:
      - echo "******** Uploading to S3 ********"
      - aws s3 rm s3://${BUCKET_NAME} --recursive
      - aws s3 cp public/ s3://${BUCKET_NAME} --recursive --content-encoding 'gzip' --cache-control "public,max-age=0,must-revalidate"
      - aws s3 cp public/ s3://${BUCKET_NAME} --recursive --exclude "*" --include "*.html" --content-encoding 'gzip' --cache-control "public,max-age=0"
      - aws s3 cp public/static s3://${BUCKET_NAME}/static --recursive --content-encoding 'gzip' --cache-control "public,max-age=31536000,immutable"