version: '3'

services:
  app: 
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - .:/app 
    ports: 
      - "8000:8000"
    environment:
      - NODE_ENV=development
      - GATSBY_WEBPACK_PUBLICPATH=/